// Random testbench for width_examples.sv. Drives zeros, all-ones, top-bit-only and random
// values and prints every port in hex; doc/rtl-style/sv-style/tools/check-width-examples.mjs checks them.
module width_examples_tb #(parameter int W = 16, parameter int N = 6, parameter int S = 3, parameter int F = 4, parameter int LIM = 100, parameter int NV = 3000);
  localparam int SW = $clog2(W);
  logic [W-1:0] a;
  logic [W-1:0] b;
  logic [N-1:0] c;
  logic signed [W-1:0] sa;
  logic signed [W-1:0] sb;
  logic signed [N-1:0] sc;
  logic [SW-1:0] sh;
  logic [W-1:0] u_add_wrap;
  logic [W:0] u_add_full;
  logic [W-1:0] u_inc;
  logic [W:0] u_add_narrow;
  logic [W-1:0] u_avg;
  logic signed [W-1:0] s_add_wrap;
  logic signed [W:0] s_add_full;
  logic signed [W-1:0] s_sub_lit;
  logic signed [W:0] s_add_narrow;
  logic signed [W+1:0] s_add_mixed;
  logic [2*W-1:0] u_mul_full;
  logic [W-1:0] u_mul_lo;
  logic [W+N-1:0] u_mul_narrow;
  logic [W+1:0] u_mul_lit;
  logic signed [2*W-1:0] s_mul_full;
  logic signed [W+2:0] s_mul_lit;
  logic signed [2*W:0] s_mul_mixed;
  logic signed [W-1:0] s_mul_q;
  logic [W-1:0] u_shl_fix;
  logic [W+S-1:0] u_shl_full;
  logic [W-1:0] u_shr_fix;
  logic [W-1:0] u_shl_var;
  logic [W-1:0] u_shr_var;
  logic [W-1:0] u_onehot;
  logic [W-1:0] u_mask;
  logic signed [W-1:0] s_sra_fix;
  logic signed [W-1:0] s_sra_var;
  logic signed [W+S-1:0] s_sla_full;
  logic signed [W-1:0] s_neg_pow;
  logic [W-1:0] u_zext;
  logic signed [W-1:0] s_sext;
  logic signed [W:0] s_from_u;
  logic [W-1:0] u_lim;
  logic [W-1:0] u_ones;
  logic [N-1:0] u_trunc;
  logic [N-1:0] u_trunc_sum;
  logic signed [N-1:0] s_trunc;
  logic [0:0] u_is_zero;
  logic [0:0] u_at_lim;
  logic [0:0] u_sum_gt;
  logic [0:0] s_is_neg;
  width_examples #(.W(W), .N(N), .S(S), .F(F), .LIM(LIM)) dut (.*);
  // 0: random, 1: zero, 2: all ones, 3: only top bit set
  function automatic logic [95:0] pick(input logic [1:0] k, input logic [95:0] r, input int w);
    case (k)
      2'd1: return '0;
      2'd2: return ~96'd0;
      2'd3: return 96'd1 << (w - 1);
      default: return r;
    endcase
  endfunction
  logic [31:0] sel;
  initial begin
    $display("PARAMS %0d %0d %0d %0d %0d", W, N, S, F, LIM);
    for (int i = 0; i < NV; i++) begin
      sel = (i < NV/2) ? 32'd0 : $urandom;
      a = $bits(a)'(pick(sel[1:0], {$urandom, $urandom, $urandom}, $bits(a)));
      b = $bits(b)'(pick(sel[3:2], {$urandom, $urandom, $urandom}, $bits(b)));
      c = $bits(c)'(pick(sel[5:4], {$urandom, $urandom, $urandom}, $bits(c)));
      sa = $bits(sa)'(pick(sel[7:6], {$urandom, $urandom, $urandom}, $bits(sa)));
      sb = $bits(sb)'(pick(sel[9:8], {$urandom, $urandom, $urandom}, $bits(sb)));
      sc = $bits(sc)'(pick(sel[11:10], {$urandom, $urandom, $urandom}, $bits(sc)));
      sh = $bits(sh)'(pick(sel[13:12], {$urandom, $urandom, $urandom}, $bits(sh)));
      #1;
      $write("V");
      $write(" a=%h", a);
      $write(" b=%h", b);
      $write(" c=%h", c);
      $write(" sa=%h", sa);
      $write(" sb=%h", sb);
      $write(" sc=%h", sc);
      $write(" sh=%h", sh);
      $write(" u_add_wrap=%h", u_add_wrap);
      $write(" u_add_full=%h", u_add_full);
      $write(" u_inc=%h", u_inc);
      $write(" u_add_narrow=%h", u_add_narrow);
      $write(" u_avg=%h", u_avg);
      $write(" s_add_wrap=%h", s_add_wrap);
      $write(" s_add_full=%h", s_add_full);
      $write(" s_sub_lit=%h", s_sub_lit);
      $write(" s_add_narrow=%h", s_add_narrow);
      $write(" s_add_mixed=%h", s_add_mixed);
      $write(" u_mul_full=%h", u_mul_full);
      $write(" u_mul_lo=%h", u_mul_lo);
      $write(" u_mul_narrow=%h", u_mul_narrow);
      $write(" u_mul_lit=%h", u_mul_lit);
      $write(" s_mul_full=%h", s_mul_full);
      $write(" s_mul_lit=%h", s_mul_lit);
      $write(" s_mul_mixed=%h", s_mul_mixed);
      $write(" s_mul_q=%h", s_mul_q);
      $write(" u_shl_fix=%h", u_shl_fix);
      $write(" u_shl_full=%h", u_shl_full);
      $write(" u_shr_fix=%h", u_shr_fix);
      $write(" u_shl_var=%h", u_shl_var);
      $write(" u_shr_var=%h", u_shr_var);
      $write(" u_onehot=%h", u_onehot);
      $write(" u_mask=%h", u_mask);
      $write(" s_sra_fix=%h", s_sra_fix);
      $write(" s_sra_var=%h", s_sra_var);
      $write(" s_sla_full=%h", s_sla_full);
      $write(" s_neg_pow=%h", s_neg_pow);
      $write(" u_zext=%h", u_zext);
      $write(" s_sext=%h", s_sext);
      $write(" s_from_u=%h", s_from_u);
      $write(" u_lim=%h", u_lim);
      $write(" u_ones=%h", u_ones);
      $write(" u_trunc=%h", u_trunc);
      $write(" u_trunc_sum=%h", u_trunc_sum);
      $write(" s_trunc=%h", s_trunc);
      $write(" u_is_zero=%h", u_is_zero);
      $write(" u_at_lim=%h", u_at_lim);
      $write(" u_sum_gt=%h", u_sum_gt);
      $write(" s_is_neg=%h", s_is_neg);
      $write("\n");
    end
    $finish;
  end
endmodule
