// Regression test for RegisterBlock's read path (TSSV#79). Writes, under sv-examples/RegisterBlock_read/:
// - regblock_read32.sv: a 32-bit block with a WO register first, a field map with gaps, a
//   register with no `registers` entry (default RW), a narrow RW, an RWU, a RAM and a ROM whose
//   windows are smaller than their alignment, and registers at 0x100 and above
// - regblock_read64.sv: a 64-bit block whose RAM window is sized in 8-byte words
// - <block>_lint_top.sv for each: a wrapper that drives the block's bus from ports, so the
//   block can be linted with `verilator --lint-only -Wall`. A module with an interface port
//   can't be the top on its own: nothing would drive the interface
//
// `make -C verilatorTB regblock_read_sim` runs this, lints both blocks and simulates
// verilatorTB/tb_RegisterBlock_read.sv against them.
import { RegisterBlock, RegisterType } from 'tssv/lib/core/Registers'
import { Memory } from 'tssv/lib/interfaces/Memory'
import { mkdirSync, writeFileSync } from 'fs'

const OUT_DIR = 'sv-examples/RegisterBlock_read'

const block32 = new RegisterBlock({ name: 'regblock_read32', busAddressWidth: 32 }, {
  wordSize: 32,
  addrMap: {
    CMD: 0x0n, // WO, and first: its case used to emit `regs.READY <= ;`
    CTRL: 0x4n, // fields with gaps at [7:3] and [31:16]
    SCRATCH: 0x8n, // no `registers` entry: a default 32-bit RW
    NARROW: 0xcn, // 12-bit RW, zero-extended on read
    STAT: 0x10n, // 16-bit RWU
    MEM: 0x20n, // RAM, 4 words: 0x20-0x2f, though 0x20 is 32-byte aligned
    TBL: 0x40n, // ROM, 2 words: 0x40-0x47
    HI: 0x100n, // needs more than 8 address bits
    FAR: 0x12340n
  },
  registers: {
    CMD: { type: RegisterType.WO },
    CTRL: {
      type: RegisterType.RW,
      fields: {
        enable: { bitRange: [0, 0] },
        mode: { bitRange: [2, 1] },
        divisor: { bitRange: [15, 8], reset: 0x10n }
      }
    },
    NARROW: { type: RegisterType.RW, width: 12 },
    STAT: { type: RegisterType.RWU, width: 16 },
    MEM: { type: RegisterType.RAM, size: 4n },
    TBL: { type: RegisterType.ROM, size: 2n },
    HI: { type: RegisterType.RW, reset: 0xa5a5a5a5n },
    FAR: { type: RegisterType.RW }
  }
}, new Memory())

const block64 = new RegisterBlock({ name: 'regblock_read64', busAddressWidth: 32 }, {
  wordSize: 64,
  addrMap: {
    CSR: 0x0n,
    BUF: 0x10n, // RAM, 2 words of 8 bytes: 0x10-0x1f
    HI: 0x100n
  },
  registers: {
    CSR: { type: RegisterType.RW },
    BUF: { type: RegisterType.RAM, size: 2n },
    HI: { type: RegisterType.RW }
  }
}, new Memory())

/** A wrapper top whose ports drive and observe the block's Memory bus and its own ports. */
function lintTop (block: RegisterBlock<Record<string, bigint>>, dataWidth: number, addrWidth: number): string {
  const name = block.name
  const IOs = (block as unknown as { IOs: Record<string, { direction: string, width?: number, isSigned?: boolean }> }).IOs
  const iface = `memory_${dataWidth}_${addrWidth}`
  const ports = [
    'input  logic clk',
    'input  logic rst_b',
    `input  logic [${addrWidth - 1}:0] ADDR`,
    `input  logic [${dataWidth - 1}:0] DATA_WR`,
    'input  logic RE',
    'input  logic WE',
    `input  logic [${addrWidth / 8 - 1}:0] WSTRB`,
    `output logic [${dataWidth - 1}:0] DATA_RD`,
    'output logic READY'
  ]
  const binds = ['.clk(clk)', '.rst_b(rst_b)', '.regs(bus)']
  for (const [port, io] of Object.entries(IOs)) {
    if (port === 'clk' || port === 'rst_b') continue
    const width = io.width ?? 1
    const range = width > 1 ? `[${width - 1}:0] ` : ''
    ports.push(`${io.direction === 'input' ? 'input ' : 'output'} logic ${io.isSigned ? 'signed ' : ''}${range}${port}`)
    binds.push(`.${port}(${port})`)
  }
  return `// Lint wrapper for ${name}: generated by ts/test/test_RegisterBlock_read.ts
module ${name}_lint_top (
  ${ports.join(',\n  ')}
);
  ${iface} bus ();
  assign bus.ADDR    = ADDR;
  assign bus.DATA_WR = DATA_WR;
  assign bus.RE      = RE;
  assign bus.WE      = WE;
  assign bus.WSTRB   = WSTRB;
  assign DATA_RD     = bus.DATA_RD;
  assign READY       = bus.READY;

  ${name} dut (
    ${binds.join(',\n    ')}
  );
endmodule
`
}

mkdirSync(OUT_DIR, { recursive: true })
for (const [block, dataWidth] of [[block32, 32], [block64, 64]] as const) {
  writeFileSync(`${OUT_DIR}/${block.name}.sv`, block.writeSystemVerilog())
  writeFileSync(`${OUT_DIR}/${block.name}_lint_top.sv`, lintTop(block, dataWidth, 32))
  console.log(`wrote ${OUT_DIR}/${block.name}.sv and ${block.name}_lint_top.sv`)
}
