// Regression test for APB_to_Memory against the Memory contract (TSSV#116). Writes, under
// sv-examples/APB_to_Memory/:
// - apb_regblock.sv: a RegisterBlock with an `apb` port, so its APB_to_Memory submodule drives
//   the block's Memory bus. It has a field register, a plain RW, an RWU, a WO and a RAM window
// - apb_regblock_lint_top.sv: a wrapper that drives the block's APB port from flat ports, so the
//   block can be linted with `verilator --lint-only -Wall`
//
// `make -C verilatorTB apb_to_memory_sim` runs this, lints the block and simulates
// verilatorTB/tb_APB_to_Memory.sv against it.
import { RegisterBlock, RegisterType } from 'tssv/lib/core/Registers'
import { APB4 } from 'tssv/lib/interfaces/AMBA/AMBA4/APB4/r0p0_0/APB4'
import { mkdirSync, writeFileSync } from 'fs'

const OUT_DIR = 'sv-examples/APB_to_Memory'

const block = new RegisterBlock({ name: 'apb_regblock', busAddressWidth: 32 }, {
  wordSize: 32,
  addrMap: {
    CTRL: 0x0n, // fields at [0], [2:1] and [15:8]
    SCRATCH: 0x4n,
    STAT: 0x8n, // 16-bit RWU
    CMD: 0xcn, // WO: reads 0
    MEM: 0x20n // RAM, 4 words: 0x20-0x2f. Reads return its last write (TSSV#80)
  },
  registers: {
    CTRL: {
      type: RegisterType.RW,
      fields: {
        enable: { bitRange: [0, 0] },
        mode: { bitRange: [2, 1] },
        divisor: { bitRange: [15, 8], reset: 0x10n }
      }
    },
    SCRATCH: { type: RegisterType.RW, reset: 0x5a5a5a5an },
    STAT: { type: RegisterType.RWU, width: 16 },
    CMD: { type: RegisterType.WO },
    MEM: { type: RegisterType.RAM, size: 4n }
  }
}, new APB4({ DATA_WIDTH: 32, ADDR_WIDTH: 32 }))

/** A wrapper top whose ports drive and observe the block's APB port and its own ports. */
function lintTop (): string {
  const IOs = (block as unknown as { IOs: Record<string, { direction: string, width?: number, isSigned?: boolean }> }).IOs
  const apbIn = [['PADDR', 32], ['PSELx', 1], ['PENABLE', 1], ['PWRITE', 1], ['PWDATA', 32], ['PPROT', 3], ['PSTRB', 4], ['PCLKEN', 1]] as const
  const apbOut = [['PRDATA', 32], ['PREADY', 1], ['PSLVERR', 1]] as const
  const range = (width: number): string => width > 1 ? `[${width - 1}:0] ` : ''
  const ports = [
    'input  logic clk',
    'input  logic rst_b',
    ...apbIn.map(([sig, width]) => `input  logic ${range(width)}${sig}`),
    ...apbOut.map(([sig, width]) => `output logic ${range(width)}${sig}`)
  ]
  const binds = ['.clk(clk)', '.rst_b(rst_b)', '.apb(bus)']
  for (const [port, io] of Object.entries(IOs)) {
    if (port === 'clk' || port === 'rst_b') continue
    ports.push(`${io.direction === 'input' ? 'input ' : 'output'} logic ${io.isSigned ? 'signed ' : ''}${range(io.width ?? 1)}${port}`)
    binds.push(`.${port}(${port})`)
  }
  return `// Lint wrapper for ${block.name}: generated by ts/test/test_APB_to_Memory.ts
module ${block.name}_lint_top (
  ${ports.join(',\n  ')}
);
  APB4_32_32 bus ();
  assign bus.PCLK    = clk;
  assign bus.PRESETn = rst_b;
${apbIn.map(([sig]) => `  assign bus.${sig} = ${sig};`).join('\n')}
${apbOut.map(([sig]) => `  assign ${sig} = bus.${sig};`).join('\n')}

  ${block.name} dut (
    ${binds.join(',\n    ')}
  );
endmodule
`
}

mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(`${OUT_DIR}/${block.name}.sv`, block.writeSystemVerilog())
writeFileSync(`${OUT_DIR}/${block.name}_lint_top.sv`, lintTop())
console.log(`wrote ${OUT_DIR}/${block.name}.sv and ${block.name}_lint_top.sv`)
